export var FETCH_MODES;
(function (FETCH_MODES) {
    FETCH_MODES["SEQUENTIAL"] = "SEQUENTIAL";
    FETCH_MODES["BATCHED"] = "BATCHED";
    FETCH_MODES["PIPELINING"] = "PIPELINING";
    FETCH_MODES["PARALLEL"] = "PARALLEL";
})(FETCH_MODES || (FETCH_MODES = {}));
;
